
server:
  port: 9098
spring:
  application:
    name: district

  datasource:
    url: jdbc:mysql://localhost:3306/ustemp
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

management:
  tracing:
    sampling:
      probability: 1.0